roboshop project

diff --git a/mongodb,sh b/mongodb,sh
--- a/mongodb,sh
+++ b/mongodb,sh
@@ -5,11 +5,11 @@ R="\e[31m"
 G="\e[32m"
 Y="\e[33m"
 N="\e[0m"
-LOGS_FOLDER="/var/log/-logs"
+LOGS_FOLDER="/var/log/roboshop-logs"
 SCRIPT_NAME=$(echo $0 | cut -d "." -f1)
 LOG_FILE="$LOGS_FOLDER/$SCRIPT_NAME.log"
-PACKAGES=("mysql" "python3" "nginx" "httpd")
 
+#check the user has root priveleges or not
 mkdir -p $LOGS_FOLDER
 echo "Script started executing at: $(date)" | tee -a $LOG_FILE
 
@@ -25,9 +25,27 @@ fi
 VALIDATE(){
   if [ $1 -eq 0 ]
    then
-      echo -e "Installing $2 is ... $G SUCCESS $N" | tee -a $LOG_FILE
+      echo -e "$2 is ... $G SUCCESS $N" | tee -a $LOG_FILE
    else
-      echo -e "Installing $2 is ... $R FAILURE $N" | tee -a $LOG_FILE
+      echo -e "$2 is ... $R FAILURE $N" | tee -a $LOG_FILE
       exit 1
    fi       
 }
+
+cp mongo.repo /etc/yum.repos.d/mongo.repo
+VALIDATE $? "Copying MongoDB repo"
+
+dnf install mongodb-org -y &>>$LOG_FILE
+VALIDATE $? "Installing mongodb server"
+
+systemctl enable mongod &>>$LOG_FILE
+VALIDATE $? "Enabling MongoDB"
+
+systemctl start mongod &>>$LOG_FILE
+VALIDATE $? "Starting MongoDB"
+
+sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mongod.conf
+VALIDATE $? "Editing MongoDB conf file for remote connections"
+
+systemctl restart mongod &>>$LOG_FILE
+VALIDATE $? "Restarting MongoDB"
